### ISSUE TITLE
Error when Fe_uv_op set as False and MCMC=True

### ISSUE THREAD

**Issue by astro-fermi** [legolason/PyQSOFit#44]
Hello,

Thanks for this great package. I just tried the latest version of PyQsoFit and attempted to estimate the uncertainties using the MCMC option. My input is as follows:

data = fits.open(os.path.join(path_ex, 'data/spec-2788-54553-0051.fits'))
lam = 10**data[1].data['loglam']        # OBS wavelength [A]
flux = data[1].data['flux']             # OBS flux [erg/s/cm^2/A]
err = 1/np.sqrt(data[1].data['ivar'])   # 1 sigma error
z = data[2].data['z'][0]                # Redshift

ra = data[0].header['plug_ra']        # RA
dec = data[0].header['plug_dec']      # DEC
plateid = data[0].header['plateid']   # SDSS plate ID
mjd = data[0].header['mjd']           # SDSS MJD
fiberid = data[0].header['fiberid']   # SDSS fiber ID

q = QSOFit(lam, flux, err, z, ra=ra, dec=dec, plateid=plateid, mjd=mjd, fiberid=fiberid, path=path_ex)

q.Fit(name=None, nsmooth=1, and_or_mask=False, deredden=True, reject_badpix=False, wave_range=None,\
      wave_mask=None, decompose_host=False, Mi=None, npca_gal=5, npca_qso=20,\
      Fe_uv_op=False, Fe_flux_range=None, poly=True, BC=False, rej_abs=False, linefit=True,\
      initial_guess=None, \
      MCMC=True, nburn=100, nsamp=200, nthin=10,  epsilon_jitter=1e-5, plot_corner=True,\
      save_result=True, plot_fig=True, save_fig=True, plot_line_name=True, plot_legend=True, \
      save_fig_path=path_out, save_fits_path=path_out, save_fits_name=None)

This gives the following error:

  File "new_pyqsofit.py", line 36, in <module>
    q.Fit(name=None, nsmooth=1, and_or_mask=False, deredden=True, reject_badpix=False, wave_range=None,\
  File "/opt/miniconda3/lib/python3.8/site-packages/PyQSOFit-1.2.0-py3.8.egg/pyqsofit/PyQSOFit.py", line 475, in Fit
    self.fit_continuum(self.wave, self.flux, self.err, self.ra, self.dec, self.plateid, self.mjd, self.fiberid)
  File "/opt/miniconda3/lib/python3.8/site-packages/PyQSOFit-1.2.0-py3.8.egg/pyqsofit/PyQSOFit.py", line 1230, in fit_continuum
    Fe_flux_results = np.empty((len(samples), np.shape(self.Fe_flux_range.flatten())[0]//2))
AttributeError: 'NoneType' object has no attribute 'flatten'

I request you to kindly take a look at the problem.

**Comment by legolason** [comment]
The lasted version is still not a stable one, you can try the old version first. @burke86  Maybe Colin is able to take a look at this issue?

**Comment by burke86** [comment]
Thanks for reporting the issue. Should be fixed in PR #45 but let us know if not.

**Comment by astro-fermi** [comment]
This problem is still persisting. I installed the new version and getting the same error now. The issue may have something to do with the following command:

Fe_flux_results = np.empty((len(samples), np.shape(self.Fe_flux_range.flatten())[0]//2))

Just to repeat, this error appears when opting for the following condition in the inputs: 

Fe_uv_op=False and MCMC=True

**Comment by burke86** [comment]
@astro-fermi OK, thanks. Try setting `Fe_flux_range=np.array([4435,4685])` until we get it fixed. As long as Fe_uv_op=False, the Fe_flux_range shouldn't matter I think. We probably just need to change it to:

`Fe_flux_results = np.empty((len(samples), np.shape(np.ravel(self.Fe_flux_range))[0]//2))
`

**Comment by burke86** [comment]
Should be solved with PR #47
